name: el_kabah_app_backup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2+1
  google_fonts: ^8.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.6.0
  flutter_qiblah: ^3.2.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/masjid.jpg
    - assets/tasbih.png
    - assets/kabah.png
    - assets/quran.png
    - assets/mosque.png
    - assets/thumbnail_yt.png
    - assets/motif.png